### ISSUE TITLE
Setup reportstream@cdc.gov email

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#1050]
### Todo:

- [ ] Create `reportstream@cdc.gov` with CDC help
- [ ] Get access to inbox for whole team

### Checklist moved from #389 (closed as duplicate), not sure if we still need to do these last two ones.

- [x] Decide on SendGrid level (possible overlap with SimpleReport) & procure
- [x] ~~Obtain support@prime.cdc.gov & no-reply@prime.cdc.gov emails~~
- [ ] Attach above accounts as senders
- [ ]  Configure organizations.yml (test/prod/local)

**Comment by drew-usds** [comment]
@mry-usds closed out duplicate issue #389 and moved things to this updated one.
