### ISSUE TITLE
Add Terms of Service page

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#1053]
### Todo:

- [ ] Move draft content to O365
- [x] Get final content approval
- [x] Create `/terms` page
- [x] HTML-ify content
- [x] Team review

**Comment by drew-usds** [comment]
Current draft shared by Amy: https://usds.slack.com/archives/C0194N192DR/p1620658061495500

**Comment by drew-usds** [comment]
Final doc from Amy: https://usds.slack.com/archives/C0194N192DR/p1621021651052300
