### ISSUE TITLE
Florida Go Live Checklist

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#109]
Overview doc = https://drive.google.com/file/d/1uCKyeW4hh2wmpahD3JHcJ9jH66sodyt0/view?usp=sharing

Checklist
- [x]  Intro 
  - [x] get documents https://drive.google.com/drive/folders/1Oed8k5AfqxdouQTPuS3bDRedNGrc6hxM
  - [x] submit registration
- [x]  Receive SFTP credentials
- [x]  Confirm data schema
Elr documentation = https://drive.google.com/file/d/1my9ftaEcqzECjWYCwnWu5VuY_2AeYQh9/view?usp=sharing
CSV = https://cdc.sharepoint.com/:x:/t/USDSatCDC/EQ44_DXxLbREub1DbMB3dw8BCuumC8UkF-8o6AK8QuXUuQ?e=EGAO2B

- [x]  Send test file
- [x]  Confirm new site registration process
- [ ] Go live

**Comment by drew-usds** [comment]
Sending CSV for now. Waiting on final steps/feedback from FL.

**Comment by MauriceReeves-usds** [comment]
I updated the fake data generation and sent a new file to FL this morning.

**Comment by MauriceReeves-usds** [comment]
This is still in progress. We have sent them another file, but we are waiting to review with them. We will send them more synthetic data this week.

**Comment by jlusds** [comment]
Blocked by first new sender

**Comment by jlusds** [comment]
Another file sent on Friday, Waiting for approval for HL7
