### ISSUE TITLE
Texas Go Live Checklist

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#114]
- [x]  Intro 
- [ ]  Receive SFTP credentials
- [ ]  Confirm data schema - tracked https://github.com/CDCgov/prime-data-hub/issues/146
- [ ]  Send test file
- [ ]  Confirm new site registration process

**Comment by jlusds** [comment]
Blocked by CDC submitting form to get SFTP credentials

**Comment by jlusds** [comment]
Latest updating, sending them another batch of files
