### ISSUE TITLE
North Dakota Go Live Checklist

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#237]
- [x]  Intro 
- [x]  Receive SFTP credentials
- [x]  Confirm data schema
- [x]  Send test file
- [x]  Confirm new site registration process

https://www.health.nd.gov/sites/www/files/documents/Files/MSS/MU/ELR_CondensedSpec.pdf

**Comment by MauriceReeves-usds** [comment]
I've created an empty PR for this and I'm reviewing the spec now.

**Comment by jlusds** [comment]
SFTP received on 1/4/21

**Comment by jlusds** [comment]
Sent request for sign off on new site registration process on 1/5/21

**Comment by MauriceReeves-usds** [comment]
Sent our first test file to ND this morning via SFTP. The file sent is in KeyBase

**Comment by jlusds** [comment]
Feedback received from ND as of 1/25 morning

**Comment by jlusds** [comment]
@MauriceReeves-usds sending another file

still waiting on first site

**Comment by jlusds** [comment]
Site confirmed, waiting to turn on
