### ISSUE TITLE
DL site: test login, pw reset, download process internally

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#246]
- [x] Create OKTA logins for team
- [x] Add dummy data to test

## General checks
- [x] Review for bugs, tweaks, edits, etc. Adding list of general things for us to check out:
  - [x] Login
  - [x] PW reset
  - [x] Logout [works but see notes below]
  - [x] Nav links
  - [x] Footer links
  - [x] Table row info for "today's data", does it match the CSV?
  - [x] Download link for "today's data"
  - [x] Table row info for previous days, does it match the CSV?
  - [x] Download links for previous days
  - [x] CSV filename
- [x] Browser check of basic features (login, download, logout)  
  - [x] Chrome Mac
  - [x] Chrome Win
  - [x] FF Mac
  - [x] FF Win
  - [x] Safari Mac (resolved ~~see below comment, "Our services aren't available right now"~~)
  - [x] Edge Win
  - [x] Older IE -> IE WIn 10: hangs on the 2FA step with Google Authenticator, can't get past it [moved to #406]
  - [x] Tablet: iOS (see below comment, "Our services aren't available right now")
  - [x] Chrome Linux
  - [x] FF LInux
  - [x] Vivaldi Linux

## MVP edits

**Login/logout/reset**
- [x] On logout, point back to the Data Hub OKTA login page
- [x] After logging out, was able to hit the back button and still see everything on the download index (Mac Chrome).
- [x] On login, the index URL has `#no-back-button` on the end. Is that easy to remove? [moved to #407]

**Nav**
- [x] Link "Prime Data Hub" to the download index.

**Header**
- [x] Change Location name "pima_az_phd" to friendlier name. Maybe ex "Pima County, AZ" or "Pima County Health Department"? (Maybe that display name is something the user could edit? Something to ask partners about)

**CSV lists**
- [x] Expires column: add plural logic to "day"/"days" 
- [x] Today's results show more than 1
- [x] Previous _n_ days: if no data available, change text from "No data found" to "No data is available for the previous _n_ days. If you think this might be in error, contact `support@prime.cdc.gov`." 
  - [x] Typo: remove trailing "`" at the end of the no data available message.
- [x] Add `GMT` to end of `Date`
- [x] For `Receiver` change to friendlier description, same as H1
- [x] Add date, location in front of filename `test-results.csv` -> maybe `YYYYMMDD-[state]-[county name]-test-results.csv`

**Footer**
- [x] Add a `target=_blank` to the CDC link in the footer
- [x] Add support email address to the footer

**Other bugs**
- [x] Favicon - copy CDC one
- [x] Change "receiver" to "description" [moved to #409]

**Comment by drew-usds** [comment]
Notes:

Overall
- What will the URL for the OKTA login be? `prime.cdc.gov`?
- Will the download index URL be `prime.cdc.gov/api/download`? Could it be `/data-hub` instead (to be updated when we have a new product name)? If that's not possible to change now that's something we can also ask Pima about.
- Is there an inactivity timeout with OKTA? I'm having to log in again a fair amount, but maybe it's also because of Matt making updates?

Nav
- Prime Data Hub text in the nav should link to the download index.

Header
- Change Location name "pima_az_phd" to friendlier name. Maybe ex "Pima County, AZ" or "Pima County Health Department"

CSV lists
- Expires column: add plural logic to "day"/"days"

Footer
- Add a `target=_blank` to the CDC link in the footer
- Add support email address to the footer

**Comment by drew-usds** [comment]
In both Safari (10.14.6) and on iOS (iPad Pro 13.5.1) I get the following on a blank page when going to the OKTA login:

``` html
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0lXELYAAAAADdp3Q84jNeRLFIy+uxKLKdQ0hHRURHRTE2MTcARWRnZQ==
```

**Comment by jlusds** [comment]
typo = 
![image](https://user-images.githubusercontent.com/70537819/106033228-5ef60e00-6086-11eb-9d13-1d4b21e0e506.png)
