### ISSUE TITLE
Louisiana Go Live Checklist

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#326]
- [x]  Intro 
- [X]  Receive SFTP credentials
- [x]  Confirm data schema https://drive.google.com/drive/u/0/folders/1cvwNu2tRJmvUOQLVcudxLaGbljlhEAvI
- [ ]  Send test file
- [ ]  Confirm new site registration process

**Comment by jlusds** [comment]
@MauriceReeves-usds have we sent the test file?

**Comment by jlusds** [comment]
Site confirmed, need to add to production and organizations.yaml @MauriceReeves-usds
