### ISSUE TITLE
Go live checklist for sending to AZ

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#47]
- [x] Establish relationship with AZ
- [X] Get details to execute
    - [x] Hosting #30 
    - [x] Authentication/Credentials (See SFTP #14 )
    - [x] CLIA certification - not needed
    - [x] Expectations on sending frequency
    - [x] Timeline (2-4 weeks)
- [x] Submit authentication form
- [x] Get credentials
- [x] Confirms we can connect to server, drop test file
- [x] AZ reviews test files
- [x] Generate multiple samples from PDI staging server, submitted to Data Hub, then exported to AZ's format
- [x] Validate data is 100%
- [ ] Once several files are received without error through test system, then move to prod system

**Todo other ...**
- [x] ~~Get Hub engineers traveling next week up to speed with SimpleReport app/install locally. May need to provide on-site help.~~

**Other questions**
-We will start with "dual sending" on production. How to make sure the data sent is same? How do we transition off from dual sending? 
-How to verify something is sent, was it received properly
-what is the difference test and prod, is it different credentials, folders, etc

**End to end**
-Be able to receive data from PDI app, agreement on schema [Jim, ask Tim]  (https://github.com/CDCgov/prime-data-hub/issues/75)
-Write postman script to test end to end process [Chris] https://github.com/CDCgov/prime-data-hub/issues/94
-Wire the SFTP sending to latest build, support USDS test SFTP, AZ's test SFTP and AZ prod modes [Matt] https://github.com/CDCgov/prime-data-hub/issues/95
-Give Chris a SFTP docker container [Matt] https://github.com/CDCgov/prime-data-hub/issues/96

-----

**Via Elegante location details**
- Starting w/ Tuscon Mountain location
- Expected testing volume: 140/week
- Heavy testing volume on Wednesday/Thursday/Sunday at 6am and 6pm MT
  - Corresponds with shift changes
- Uses BD and BinaxNOW machines

**Comment by jlusds** [comment]
11/18 update - submitted authentication form, awaiting credentials

**Comment by jlusds** [comment]
Credentials received!

**Comment by jlusds** [comment]
Status based on convo with Eli:
Based on your feedback, we will send real patient data next week to the test environment. During this time, the test facility will continue to submit via Google Form. After your feedback and sign off, then we will switch over to sending via production.

**Comment by jlusds** [comment]
Eli + Jim reviewed an updated round of test data

From Eli:

"  These notes look accurate.          

I have confirmed that we are Ok to receive the expanded values for administrative sex that were seen in your test file. 

I have also determined that our preference would be to receive two separate files from USDS, one for all TEST submitters, and one for all PROD submitters. The TEST file should be placed in the TEST/IN SFTP folder and the PROD file should be placed in the PROD/IN SFTP folder."
