### ISSUE TITLE
Harden the API end-points

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-data-hub#495]
As a security professional, I would like to see the DH's end-points hardened against malicious attacks that manipulate the payload sent through the data hub. 

**Goals**
The API end-points should have a number of limits, checks and validations that prevents from an attacker who knows about the inner workings of the data hub (ie. read our source code) from information disclosure and service disruption. 

This epic is not about DDOS attacks which will be handled by the WAF epics. 

**Acceptance Criteria**
- [X] SQL injection protection by design
- [X] Limits on report size overall size
- **ICEBOX**: URL hashing in the of the data hubs reports end-point

Tasks:
- [X] SQL injection protection: Fix the "LIKE" query currently used for download. 
- [X] Limits:  Write brief proposal on how to do data element limits
- [X]  Limits: Impl report size 
- [X] What are the threats we're trying to avoid by using URL hashing?      Requires an additional secret known by the sender to use as a salt.

Moved to other tickets.
- [ ] Impl element size limits
- [ ] Expiring URLs.
