### ISSUE TITLE
Go live checklist for sending to Pima

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-data-hub#89]
User needs checklist
- [x] Get sign off on file format
- [x] Get sign off on legal agreements - non required
- [x] Get sign off on when to send, and to whom
- [x] Get accounts set up [Admin account from @RickHawesUSDS for @mry-usds ]
- [x] Send test data and get sign off from them
- [x] Send prod data and get sign of from them, tell pilot they can stop dual reporting

**Format**
Format of the file is this file https://drive.google.com/file/d/1DqNdMRTU2jMO3i_rNUyB10DBhLa-Htnz/view?usp=sharing + the two additional columns
1) Date of symptom onset
2) Device type (blocked by https://github.com/CDCgov/prime-data-hub/issues/100)

**Operations*
Expect a notification everyday at 8am MST
Can download their own files, assume files will be data from last 24 hours

**Eng requirements for MVP**
Webpage
Authentication + credentialing
Logic to delete data after 7 days (we can do this manually if needed?)
Notification (we can do this manually if needed?)

**Comment by jlusds** [comment]
11/18 update - awaiting sign off on file format (expected 11/20), asked for legal agreements

**Comment by jlusds** [comment]
Confirmed from Kat no legal agreement requirements

**Comment by jlusds** [comment]
@drew-usds we'll need a design for the email we send

**Comment by jlusds** [comment]
Confirmed email addresses, time from Pima

**Comment by jlusds** [comment]
Sending Pima updated Okta proposal today
