### ISSUE TITLE
County CSV download process

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-data-hub#91]
## Overview
As a county PHD employee, I want to be able to access and download a recent history of submitted test data. Possible use cases:

- I may not have a connection to a state system, or am not fully connected to Data Hub and need access to data asap.
- I am fully connected to Data Hub, but there is a submission error or an error with other internal systems and I need to re-download.

**General flow**
- Notified of new test results by email #60 
- Auth via OKTA
- Basic UI
  - Name of County, name of reporting location
  - Index of submissions w/download link(s)
    - `<li>` contains [submission date, # of results, filename/link, expiration date]
  - Logout link
  - PW reset

**Need to figure out**
- [x] Email sending system
- [ ] Storage & data retention policy

## Todo

**UX**
- [x] Create mockup
- [x] Check in w/Pima 11/25 for feedback on mockups @jlusds @drew-usds 

**Login**
- [ ] OKTA from SimpleReport. Same instance, new group @mry-usds . @jlusds to connect with Input team
- [ ] Create accounts for each Pima user @mry-usds 
- [ ] Mock up PW reset options @drew-usds 

**Front end**
- [x] Build from SimpleReport React components @mry-usds (no longer need React, just basic HTML & CSS)

**Email**
- [x] HTML in `assets` dir @drew-usds see #60

**Comment by drew-usds** [comment]
Draft mockup on Figma: 

https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/Download-site?node-id=0%3A1

**Comment by jlusds** [comment]
Sent Pima an overview of sign up flow, got sign off from SimpleReport team to use same Okta instance

**Comment by drew-usds** [comment]
Just created a PR for this (#129 ) @mry-usds . 

Here's what it's looking like on my localhost:

<img width="1348" alt="Screen Shot 2020-12-04 at 10 35 26 PM" src="https://user-images.githubusercontent.com/57154955/101233150-8337fe80-3684-11eb-9308-5fd11e72ae2d.png">
